/**
 * Server types — auto-generated by scripts/sync-types.sh
 * DO NOT EDIT MANUALLY. Run `npm run sync-types` to update.
 *
 * AppRouter type is resolved via tsconfig path alias
 * "@server/*" → "../app/src/*" (see tsconfig.json)
 */
export type { AppRouter } from "@server/routers";
