#!/bin/bash
# sync-types.sh
#
# Copies TypeScript types from the backend (app/src/) into the mobile app
# so tRPC client can reference the AppRouter type and DTO types.
#
# Strategy: We DON'T copy the router file (it imports all server code).
# Instead, we configure tsconfig paths to point at the backend source
# so TypeScript can resolve the AppRouter type at compile time.
# We DO copy standalone DTO files that have no server imports.
#
# Usage: npm run sync-types  (from mobile-app/)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MOBILE_ROOT="$(dirname "$SCRIPT_DIR")"
BACKEND_ROOT="$MOBILE_ROOT/../app"
TARGET_DIR="$MOBILE_ROOT/src/types/server"

echo "🔄 Syncing types from backend → mobile-app..."

# Verify backend exists
if [ ! -d "$BACKEND_ROOT/src" ]; then
  echo "❌ Backend not found at $BACKEND_ROOT/src"
  exit 1
fi

# Clean target
rm -rf "$TARGET_DIR"
mkdir -p "$TARGET_DIR/dto"

# Copy DTOs (standalone type files with no server imports)
if [ -d "$BACKEND_ROOT/src/types/dto" ]; then
  cp "$BACKEND_ROOT/src/types/dto/"*.ts "$TARGET_DIR/dto/"
  echo "  ✅ DTOs copied ($(ls "$TARGET_DIR/dto/" | wc -l | tr -d ' ') files)"
fi

# Copy context types
if [ -f "$BACKEND_ROOT/src/types/context.ts" ]; then
  cp "$BACKEND_ROOT/src/types/context.ts" "$TARGET_DIR/context.ts"
  echo "  ✅ Context types copied"
fi

# Create barrel export
cat > "$TARGET_DIR/index.ts" << 'EOF'
/**
 * Server types — auto-generated by scripts/sync-types.sh
 * DO NOT EDIT MANUALLY. Run `npm run sync-types` to update.
 *
 * AppRouter type is resolved via tsconfig path alias
 * "@server/*" → "../app/src/*" (see tsconfig.json)
 */
export type { AppRouter } from "@server/routers";
EOF

echo "✅ Type sync complete → $TARGET_DIR"
echo ""
echo "Files synced:"
find "$TARGET_DIR" -type f -name "*.ts" | sort | while read f; do
  echo "  $(basename "$f")"
done
