#!/bin/bash
# sync-types.sh
#
# Copies TypeScript types from the backend (app/src/) into the mobile app
# so tRPC client can reference the AppRouter type and DTO types.
#
# Usage: npm run sync-types  (from mobile-app/)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MOBILE_ROOT="$(dirname "$SCRIPT_DIR")"
BACKEND_ROOT="$MOBILE_ROOT/../app"
TARGET_DIR="$MOBILE_ROOT/src/types/server"

echo "🔄 Syncing types from backend → mobile-app..."

# Verify backend exists
if [ ! -d "$BACKEND_ROOT/src" ]; then
  echo "❌ Backend not found at $BACKEND_ROOT/src"
  exit 1
fi

# Clean target
rm -rf "$TARGET_DIR"
mkdir -p "$TARGET_DIR/dto"

# Copy router index (AppRouter type)
cp "$BACKEND_ROOT/src/routers/index.ts" "$TARGET_DIR/router.ts"

# Copy DTOs
if [ -d "$BACKEND_ROOT/src/types/dto" ]; then
  cp "$BACKEND_ROOT/src/types/dto/"*.ts "$TARGET_DIR/dto/"
  echo "  ✅ DTOs copied"
fi

# Copy context types
if [ -f "$BACKEND_ROOT/src/types/context.ts" ]; then
  cp "$BACKEND_ROOT/src/types/context.ts" "$TARGET_DIR/context.ts"
  echo "  ✅ Context types copied"
fi

# Create a barrel export with just the AppRouter type
cat > "$TARGET_DIR/index.ts" << 'EOF'
/**
 * Server types — auto-generated by scripts/sync-types.sh
 * DO NOT EDIT MANUALLY. Run `npm run sync-types` to update.
 */

// Re-export the AppRouter type for tRPC client
// NOTE: This file only re-exports the TYPE. The actual router code is not
// bundled in the mobile app — only the type information is used.
export type { AppRouter } from "./router";
EOF

echo "✅ Type sync complete → $TARGET_DIR"
echo ""
echo "Files synced:"
find "$TARGET_DIR" -type f -name "*.ts" | sort | while read f; do
  echo "  $(basename "$f")"
done
